server:
  port: 8088

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.identicum: DEBUG



# We developed a custom Converter for parsing the Keycloak client roles 
# If you want to use it, you must follow the syntax: 'keycloak-client-role:{client_id}'
# Otherwise just put the claim name that you want to use for identifying the permission claim
claim:
  roles:
     claim-name: keycloak-client-role:product-api
#    claim-name: permissions

# https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:8080/auth/realms/HrvatskiTelekom/protocol/openid-connect/certs
